"""add domain_age_years to websites

Revision ID: 80576dc0a09a
Revises: dea96aa474f3
Create Date: 2026-09-14 23:42:01.479495

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80576dc0a09a'
down_revision: Union[str, None] = 'dea96aa474f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('domain_age_years', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'domain_age_years')
    # ### end Alembic commands ###
