"""add deal status tracking

Revision ID: 843da0616461
Revises: 80576dc0a09a
Create Date: 2026-09-15 11:58:50.340924

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '843da0616461'
down_revision: Union[str, None] = '80576dc0a09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_activities',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'REPLIED', 'INTERESTED', 'NOT_INTERESTED', 'DO_NOT_CONTACT', 'CONVERTED', name='deal_status'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default backfills the 86 existing rows created before this
    # column existed -- autogenerate doesn't add this automatically, and
    # without it this ALTER TABLE ADD COLUMN NOT NULL fails outright
    # against a populated table.
    op.add_column(
        'businesses',
        sa.Column(
            'deal_status',
            sa.Enum('NEW', 'CONTACTED', 'REPLIED', 'INTERESTED', 'NOT_INTERESTED', 'DO_NOT_CONTACT', 'CONVERTED', name='deal_status'),
            nullable=False,
            server_default='NEW',
        ),
    )
    op.add_column('businesses', sa.Column('deal_status_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'deal_status_updated_at')
    op.drop_column('businesses', 'deal_status')
    op.drop_table('deal_activities')
    # ### end Alembic commands ###
