"""add discovery provenance fields to businesses

Revision ID: e9777b60f84b
Revises: f152a9b599cb
Create Date: 2026-09-13 22:17:15.601627

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9777b60f84b'
down_revision: Union[str, None] = 'f152a9b599cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('source_name', sa.String(length=50), nullable=True))
    op.add_column('businesses', sa.Column('source_ref', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'discovered_at')
    op.drop_column('businesses', 'source_ref')
    op.drop_column('businesses', 'source_name')
    # ### end Alembic commands ###
